export interface Project {
  id?: number | undefined;
  title?: string | undefined;
  subtitle?: string | undefined;
  status?: string | undefined;
  type?: string | undefined;
  year?: string | undefined;
  company?: string | undefined;
  companywebsite?: string | undefined;
  imageUrl?: string | undefined;
  imageUrl1?: string | undefined;
  imageUrl2?: string | undefined;
  imageUrl3?: string | undefined;
  imageUrl4?: string | undefined;
  imageUrl5?: string | undefined;
  slug?: string | undefined;
  header1?: string | undefined;
  section1?: string | undefined;
  header2?: string | undefined;
  section2?: string | undefined;
  header3?: string | undefined;
  section3?: string | undefined;
  header4?: string | undefined;
  section4?: string | undefined;
  header5?: string | undefined;
  section5?: string | undefined;
}